name: Rhino CI

on:
  push:
    branches: [ html-fork ]
  pull_request:
    branches: [ html-fork ]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Some tests require more CPU, and all can use multiple CPUs
      max-parallel: 1
      matrix:
        java: [ '11', '17', '21' ]
    name: Rhino Java ${{ matrix.java }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.6.0
    - name: Check out test262
      # We don't actually want all the history for this part
      run: git submodule update --init --single-branch
    - name: Set up Java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.2.1
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Check everything with Gradle
      run: |
        ./gradlew :rhino-all:build
        java -jar rhino-all/build/libs/rhino-*.jar
    - name: Upload results
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: reports-java-${{ matrix.java }}
        path: '*/build/reports'
    - name: Upload jar
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: jar-libs-${{ matrix.java }}
        path: '*/build/libs'
