name: Rhino CI

on:
  push:
    branches: [ html-fork ]
  pull_request:
    branches: [ html-fork ]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
    name: Rhino Java ${{ matrix.java }}
    steps:
    - name: Check out Rhino
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2
    - name: Set up Java
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Check everything with Gradle
      run: |
        ./gradlew clean
        ./gradlew --info --stacktrace --no-daemon :rhino-all:build
        java -jar rhino-all/build/libs/rhino-*.jar
    - name: Upload results
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: reports-java-${{ matrix.java }}
        path: '*/build/reports'
    - name: Upload jar
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: jar-libs-${{ matrix.java }}
        path: '*/build/libs'
